name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    uses: krakcons/krakstack/.github/workflows/project-deploy.yml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      build_image: true
      build_context: .
      dockerfile: Dockerfile
      project_slug: krakstack-template-prod
      krak_group: kt-app
      krak_task: template
      vite_site_url: https://template.krakstack.net
      vite_krakstack_auth_url: https://auth.krakstack.net
      vite_krakstack_auth_project_id: project_ilC2KI7YOZeQml2vOXsJmQD3JZOUvDg9
      vite_analytics_website_id: 274647a1-e738-4217-9006-ccbb464f0b08
    secrets:
      KRAK_RELEASE_TOKEN: ${{ secrets.KRAK_RELEASE_TOKEN }}
